- src/Vlc.DotNet.Forms/VlcControl.cs
> Don't throw NullReferenceException when GetCurrentMedia is called before EndInit()

- src/Vlc.DotNet.Core.Interops/Signatures/InteropObjectInstance.cs
- src/Vlc.DotNet.Core.Interops/VlcEventManagerInstance.cs
- src/Vlc.DotNet.Core.Interops/VlcInstance.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.cs
- src/Vlc.DotNet.Core.Interops/VlcMediaInstance.cs
- src/Vlc.DotNet.Core.Interops/VlcMediaPlayerInstance.cs
VlcControl throw unhandled exception while Disposing if:
1. set wrong VlcDirectory
2. catch exception which Play() metod throw
3. close app
> fix Disposing with wrong VlcLibDirectory

- src/Vlc.DotNet.Forms/VlcControl.cs
TakeSnapshot() functionality has been implemented into Vlc.DotNet, but TakeSnapshot() function is not accessible from VlcControl. Added method to access snapshot functionality from VlcControl.
> Make TakeSnapshot() command accessible from VlcControl

- src/Vlc.DotNet.Core.Interops/VlcManager.IsPlaying.cs
Fix the unhandled exception 'System.ArgumentException' occurred in Vlc.DotNet.Core.Interops.dll thrown on close.
> unhandled exception 'System.ArgumentException' on close

- src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media_player.h/libvlc_audio_get_track_description.cs
- src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media_player.h/libvlc_track_description_list_release.cs
- src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media_player.h/libvlc_video_get_spu_description.cs
- src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media_player.h/libvlc_video_get_track_description.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.GetAudioTracksDescriptions.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.GetVideoSpuDescription.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.GetVideoTracksDescriptions.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.ReleaseTrackDescription.cs
- src/Vlc.DotNet.Core/TrackDescription.cs
Changed from struct to pointer in the vlclib api mapping regarding track description structure, since this raised a pinvoke exception of bad mapping on the methods that returned the struct.
Also fixed an issue with the encoding of the name contained in the string, since with vlc 2.4 on windows 7, the UTF-8 encoded name property of the struct is marshalled as ansi. Switching to unicode gives asian characters.
All issues were detected and fixed only on .net 4.5 since this is the version I am using. As such I am unsure if these issues exist on the other .net framework versions.
> Subtitle marshalling error

- src/Samples/Vlc.DotNet.Forms.Samples/Sample.cs
- src/Samples/Vlc.DotNet.Wpf.Samples/MainWindow.xaml.cs
fixed Samples by choosing the libraries to load based on IntPtr.Size rather than on the host OS CPU architecture
> Fixed AnyCPU samples projects running on x64 host that won't load the DLLs from the correct folder

- src/Vlc.DotNet.Core/VlcMediaPlayer/VlcMediaPlayer.Events.Log.cs
- src/Vlc.DotNet.Core/VlcMediaPlayer/VlcMediaPlayerLogEventArgs.cs
Fixed an issue where the vlc was blocked because of the user's logging method taking too much time before returning.
Solution : launch the event from another thread from the `ThreadPool`
> Logging fix

- src/Vlc.DotNet.Core.Interops/Signatures/libvlc.h/libvlc_new.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.AddOptionToMedia.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.CreateNewInstance.cs
Added support for UTF-8 in options, which fixes #74.
You can now put special characters in marquee! Example (vlc 3.0 only for emoji support)
```
myControl.MediaPlayer.VlcMediaplayerOptions = new[] { "--sub-source=marq{marquee=testç 👍,color=16776960}" };
```
> Fixed #74 by adding support for UTF-8 in options

- nuget/Vlc.DotNet.Core.Interops.nuspec
- nuget/Vlc.DotNet.Core.nuspec
- nuget/Vlc.DotNet.Forms.nuspec
- nuget/Vlc.DotNet.Wpf.nuspec
#308 will make this fix obsolete.
The NuGet packages produced by Vlc.DotNet are invalid. The assemblies are located in `lib\{TFM}\AnyCPU\`, but the NuGet specifications do not allow for an `AnyCPU` subfolder. Instead, the libraries should just go in `lib\{TFM}`.
I hit this on Visual Studio 2017; perhaps newer NuGet versions are a bit more strict about the folder structure.
This PR fixes that.
Fixes #276
Obsoletes #300
Fixes NuGet/Home#4417
Fixes NuGet/Home#4259
Fixes NuGet/Home#5678
> Fix NuGet package format

- src/Vlc.DotNet.Core.Interops/VlcInstance.cs
Right now this would throw a `NullReferenceException` when `instance` is null.
`IntPtr.Zero` is the unmanaged equivalent of `null`.
> Convert an null reference to VlcInstance to IntPtr.Zero

- src/Vlc.DotNet.Core.Interops/VlcManager.CreateMediaPlayer.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.CreateNewMediaFromLocation.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.CreateNewMediaFromPath.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.GetAudioFilterList.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.GetAudioOutputDeviceCount.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.GetAudioOutputDeviceLongName.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.GetAudioOutputDeviceName.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.GetAudioOutputsDescriptions.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.GetVideoFilterList.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.SetAudioOutput.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.SetLog.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.cs
Before using myVlcInstance, make sure it is not null. If it is, throw a descriptive error message.
> Validate myVlcInstance before passing it to unmanaged code.

- src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media.h/libvlc_media_new_fd.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.CreateNewMediaFromFileDescriptor.cs
Adds `VlcMediaInstance.CreateNewMediaFromFileDescriptor` which wraps around `libvlc_media_new_fd`.
> Add support for libvlc_media_new_fd

- src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media.h/libvlc_media_new_callbacks.cs
- src/Vlc.DotNet.Core.Interops/StreamData.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.CreateNewMediaFromStream.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.cs
- src/Vlc.DotNet.Core/VlcMedia/VlcMedia.cs
This is #207 with some patches applied. I've kept the original commit; if you'd rather have the original author amend his PR that's also fine with me.
This adds support for playing videos based on .NET Stream objects. It requires VLC 3.0.
Changes w.r.t. #207:
- Allocate a buffer per stream which is used for copying data. This avoids having to allocate a new `byte[]` array every time `CallbackReadMedia` is called. This has a fairly important performance impact.
- The `Stream` does not have to be seekable
- The code performs a version check and throws an exception when not on VLC 3.0
- Some cleanup
> Support playing videos from Stream objects

- CHANGELOG.md
- src/Vlc.DotNet.Core/VlcMediaPlayer/VlcMediaPlayer.cs
- src/Vlc.DotNet.Forms/VlcControl.cs
It allows users to unlock features that are not yet implemented/too low-level to be implemented in the VlcControl.
What do you think about this? Is it too dangerous to let users play with the internals of this library?
Fixes #239
> [RFC]Exposed Core.VlcMediaPlayer and Interops.VlcManager

- src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media.h/libvlc_media_add_option.cs
- src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media.h/libvlc_media_add_option_flag.cs
- src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media.h/libvlc_media_new_location.cs
- src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media.h/libvlc_media_new_path.cs
- src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media.h/libvlc_media_set_meta.cs
- src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media_player.h/libvlc_audio_output_device_id.cs
- src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media_player.h/libvlc_audio_output_device_longname.cs
- src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media_player.h/libvlc_audio_output_device_set.cs
- src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media_player.h/libvlc_audio_output_set.cs
- src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media_player.h/libvlc_video_set_aspect_ratio.cs
- src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media_player.h/libvlc_video_set_crop_geometry.cs
- src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media_player.h/libvlc_video_set_deinterlace.cs
- src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media_player.h/libvlc_video_set_logo_string.cs
- src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media_player.h/libvlc_video_set_marquee_string.cs
- src/Vlc.DotNet.Core.Interops/Utf8InteropStringConverter.cs
- src/Vlc.DotNet.Core.Interops/Utf8StringHandle.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.AddOptionFlagToMedia.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.AddOptionToMedia.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.CreateNewMediaFromLocation.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.CreateNewMediaFromPath.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.GetAudioOutputDeviceLongName.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.GetAudioOutputDeviceName.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.SetAudioOutput.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.SetAudioOutputDevice.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.SetMediaMeta.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.SetVideoAspectRatio.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.SetVideoCropGeometry.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.SetVideoDeinterlace.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.SetVideoLogo.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.SetVideoMarquee.cs
Rename `SafeUnmanagedMemoryHandle` to `Utf8StringHandle` - it's now used in a strongly typed fashion rather than `DangerousGetHandle()`
The `CLR` will marshal a `SafeHandle` to and from `IntPtr` automatically which makes the delegates strongly typed, you can only pass in a Utf8StringHandle which is created through Utf8InteropStringConverter. Should make the API more readable.
All the `InteropObjectInstance` classes could be removed and the delegates could be changed to use `SafeHandles`, make the code more readable/maintainable in my opinion.
Let me know what you think.
> Strongly type UTf8 strings using SafeHandle

- src/Vlc.DotNet.Core.Interops/Signatures/libvlc_events.h/libvlc_event_t.cs
- src/Vlc.DotNet.Core/VlcMediaPlayer/VlcMediaPlayer.Events.TitleChanged.cs
- src/Vlc.DotNet.Core/VlcMediaPlayer/VlcMediaPlayerTitleChangedEventArgs.cs
- src/Vlc.DotNet.Forms/VlcControl.Events.cs
Fix System.AccessViolationException when playing files with a title in the metadata.
Title was being treated as a string but represents the index of the "Title" being played.
> #362 Fix bug in media title

- src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media_player.h/libvlc_video_take_snapshot.cs
- src/Vlc.DotNet.Core.Interops/VlcManager.TakeSnapshot.cs
- src/Vlc.DotNet.Core/VlcMediaPlayer/VlcMediaPlayer.cs
- Allow unicode file names
- Allow the selection of a folder rather than a file (string rather than
FileInfo)
- Allow the selection of the video output where the snapshot should be
taken. This is to align Vlc.DotNet with the libvlc API.
> Refactoring of the TakeSnapshot method

- src/Samples/Samples.WinForms.Minimal/Samples.WinForms.Minimal.csproj
Used project references rather than library reference (where does that came from in the first place?)
> Fixed build warning of Samples.WinForms.Minimal

- CHANGELOG.md
- src/Vlc.DotNet.Wpf/VlcControl.cs
- src/Vlc.DotNet.Wpf/VlcVideoSourceProvider.cs
Just a small change to make videos with alpha channel supported.
You can test it if `IsAlphaChannelEnabled` property in `VlcVideoSourceProvider` is set to true and play video with alpha channel like one of [this](http://vidvox.net/media_share/pacificCoastDemoHap480p.zip)
> Adding support of rendering videos with alpha channel

- src/Vlc.DotNet.Core.Interops/VlcMediaInstance.cs
- src/Vlc.DotNet.Core/VlcMedia/VlcMedia.cs
- src/Vlc.DotNet.Core/VlcMediaPlayer/VlcMediaPlayer.cs
As pointed out by some users and suffered in my own projects there were some multithreading issues when multiple viewers are playing inside the same application.
I found most of the issues to be regarding access to very specific dictionaries.
These dictionaries were not thread-safe, and updates to them could end in errors like:
NullReferenceException.
Key not present in the dictionary
and memory access exceptions.
In particular access to:
**LoadedMedias** and **RegisterEvents(**) in VlcMedia classs
and **AllInstances** inside VlcMediaInstance
I tested those changes inside an applicacion playing 32 streams simultaneously. Without the changes an exception was fired in less than 12 hours. With the changes the application does work longer. (my isses now are more related to libVlc leaking …
> Issue 430 Multiplayer Exceptions

- src/Vlc.DotNet.Wpf/VlcVideoSourceProvider.cs
> Fixed exception if Width/Height is not known in WPF's source provider.

- src/Vlc.DotNet.Core.Interops/VlcLibraryLoader.cs
- src/Vlc.DotNet.Core/VlcMediaPlayer/VlcMediaPlayer.Events.Log.cs
I have a use-case where I open many viewers (6-9) at once and when I'm done, I dispose of them all too. I encountered two exceptions. 
Issue #639 -- a null reference exception
Issue #640 -- an index out of range exception
I believe this pull request fixes both those issues because I've been using the modified .dlls in my solution for a few days without these exceptions reoccurring.
> Disposing many viewers at once fixes

- CHANGELOG.md
- src/Vlc.DotNet.Core.Interops/VlcManager.CreateNewMediaFromStream.cs
Increased the buffer size to match VLC buffer size
Related to #647
> Declared non-seekable streams as non-seekable in callback input
