src/Vlc.DotNet.Core/VlcMediaPlayer/VlcMediaPlayer.cs
fix #14 winform sample crash if open app and then close
=> fix VlcMediaPlayer Disposing

src/Vlc.DotNet.Core.Interops/Vlc.DotNet.Core.Interops - CLR 2 - .Net 2.0.csproj, src/Vlc.DotNet.Core.Interops/Vlc.DotNet.Core.Interops - CLR 2 - .Net 3.5.csproj, src/Vlc.DotNet.Core.Interops/Vlc.DotNet.Core.Interops - CLR 4 - .Net 4.0.csproj, src/Vlc.DotNet.Core.Interops/Vlc.DotNet.Core.Interops - CLR 4 - .Net 4.5.csproj, src/Vlc.DotNet.Core.Interops/VlcInstance.cs, src/Vlc.DotNet.Core.Interops/VlcManager.CreateNewInstance.cs, src/Vlc.DotNet.Core.Interops/VlcManager.ReleaseInstance.cs, src/Vlc.DotNet.Core.Interops/VlcManager.cs
=> Changed misspelled class name "VlcIntance" -> "VlcInstance"

src/Vlc.DotNet.Core/VlcMediaPlayer/VlcMediaPlayer.cs
Fixed missing instance register for property management update after reset
=> Fixed missing instance register for management

src/Vlc.DotNet.Core/VlcMediaPlayer/VlcMediaPlayer.cs, src/Vlc.DotNet.Forms/VlcControl.cs
Description in issue #86 as workaround and i mean this fixes also #83
=> Extend VlcMediaPlayer with additional options.

src/Samples/Vlc.DotNet.Wpf.Samples/MainWindow.xaml.cs, src/Vlc.DotNet.Forms/VlcControl.cs
VlcControl.myVlcMediaPlayer not initial
=> wpf samples can't play media

src/Samples/Vlc.DotNet.Forms.Samples/Sample.cs
=> Fix "Exception has been thrown by the target of an invocation" on stop

src/Vlc.DotNet.Core/VlcMediaPlayer/VlcMediaPlayer.cs
=> empty list in static dictionary so that content can be garbage-collected

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, CHANGELOG.md
Please read contribution guidelines and give feedback.
If no feedback in a few days, this will be merged and will be considered as this repository's rules.
=> Added contribution guidelines, issue template and changelog (since v2.1.142)

CHANGELOG.md, appveyor.yml
attempts to build a "-develop" version based on the develop branch
=> Beta builds

src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media_player.h/libvlc_video_cleanup_cb.cs, src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media_player.h/libvlc_video_display_cb.cs, src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media_player.h/libvlc_video_format_cb.cs, src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media_player.h/libvlc_video_lock_cb.cs, src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media_player.h/libvlc_video_set_callbacks.cs, src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media_player.h/libvlc_video_set_format_callbacks.cs, src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media_player.h/libvlc_video_unlock_cb.cs, src/Vlc.DotNet.Core.Interops/VlcMediaPlayerInstance.SetCallbacks.cs, src/Vlc.DotNet.Core.Interops/VlcMediaPlayerInstance.SetFormatCallbacks.cs, src/Vlc.DotNet.Core.Interops/VlcMediaPlayerInstance.cs
Unless I missed them, they were not yet implemented.
=> Add support for VlcMediaPlayerInstance SetCallbacks and SetFormatCallbacks

CHANGELOG.md, src/Vlc.DotNet.Forms/VlcControl.cs
=> Added TakeSnapshot overloads.

src/Vlc.DotNet.Core.Interops/Vlc.DotNet.Core.Interops.csproj, src/Vlc.DotNet.Core/Vlc.DotNet.Core.csproj, src/Vlc.DotNet.Forms/Vlc.DotNet.Forms.csproj, src/Vlc.DotNet.Wpf/Vlc.DotNet.Wpf.csproj
=> Added back the package description

src/Vlc.DotNet.sln
the sln file was not commited after #326 . My bad. [skip ci]
=> File not renamed in sln file

appveyor.yml
=> Version bump 2.2.2

src/Samples/Vlc.DotNet.Wpf.Samples/MainWindow.xaml, src/Samples/Vlc.DotNet.Wpf.Samples/MainWindow.xaml.cs, src/Vlc.DotNet.Core/VlcMediaPlayer/VlcMediaPlayer.cs, src/Vlc.DotNet.Forms/VlcControl.cs, src/Vlc.DotNet.Wpf/VlcControl.cs
=> Correctly dispose the Wpf control

src/Vlc.DotNet.Wpf/VlcVideoSourceProvider.cs
I forgot to add libvlc initialization options in the WPF control. This is now fixed.
=> added libvlc initialization options back

src/Samples/Samples.WinForms.InitWithCode/App.config, src/Samples/Samples.WinForms.InitWithCode/Form1.Designer.cs, src/Samples/Samples.WinForms.InitWithCode/Form1.cs, src/Samples/Samples.WinForms.InitWithCode/Program.cs, src/Samples/Samples.WinForms.InitWithCode/Properties/AssemblyInfo.cs, src/Samples/Samples.WinForms.InitWithCode/Samples.WinForms.InitWithCode.csproj, src/Samples/Samples.WinForms.InitWithCode/packages.config, src/Vlc.DotNet.sln
Rather than adding it in the designer
Replaces #496
=> Added a WinForms sample for initialization from code

src/Vlc.DotNet.Wpf/VlcVideoSourceProvider.cs
Correct video width and height according to TrackInfo
=> Adapted VideoFormat() callback

src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media_player.h/libvlc_get_fullscreen.cs, src/Vlc.DotNet.Core.Interops/Signatures/libvlc_media_player.h/libvlc_set_fullscreen.cs, src/Vlc.DotNet.Core.Interops/VlcManager.GetFullScreen.cs, src/Vlc.DotNet.Core.Interops/VlcManager.SetFullScreen.cs, src/Vlc.DotNet.Core/IVideoManagement.cs, src/Vlc.DotNet.Core/VideoManagement.cs
Replaces #514, rebased on develop
Based on work by
- @LinoBarreca on Apr 17, 2015 (https://github.com/ZeBobo5/Vlc.DotNet/issues/44#issuecomment-93967821)
- @samarthshroff #514
=> Added binding for fullscreen functions

appveyor.yml, src/Vlc.DotNet.Forms/VlcControl.cs
=> Fixes TakeSnapshot parameters usage in WinForms

CHANGELOG.md, README.md, src/Samples/Samples.Core.Recording/Samples.Core.Recording.csproj, src/Samples/Samples.Core.Streaming/Samples.Core.Streaming.csproj, src/Samples/Samples.Core.Thumbnailer/Samples.Core.Thumbnailer.csproj, src/Samples/Samples.WinForms.Advanced/Samples.WinForms.Advanced.csproj, src/Samples/Samples.WinForms.InitWithCode/Samples.WinForms.InitWithCode.csproj, src/Samples/Samples.WinForms.Minimal/Samples.WinForms.Minimal.csproj, src/Samples/Samples.WinForms.MultiplePlayers/Samples.WinForms.MultiplePlayers.csproj, src/Samples/Samples.Wpf.Advanced/Samples.Wpf.Advanced.csproj, src/Samples/Samples.Wpf.Dialogs/Samples.Wpf.Dialogs.csproj, src/Samples/Samples.Wpf.Image/Samples.Wpf.Image.csproj, src/Samples/Samples.Wpf.Minimal.UsingWinForms/Samples.Wpf.Minimal.UsingWinForms.csproj, src/Samples/Samples.Wpf.Minimal/Samples.Wpf.Minimal.csproj, src/Vlc.DotNet.Forms/Vlc.DotNet.Forms.csproj
- Updated libvlc projects in samples
- Updated CHANGELOG
- Added notice on README.md about LibVLCSharp
=> Packages updates, and updated project news
